---
connections:
  type: "object"
  required: false
  properties:
    default:
      type: "object"
      properties:
        host:
          description: "Database hostname"
          type: "string"
          secret: false
          required: true
        user:
          description: "Username for DB"
          type: "string"
          secret: false
          required: true
        pass:
          description: "Password used to authenticate."
          type: "string"
          secret: true
          required: true
        db:
          description: "Name of database."
          type: "string"
          secret: false
          required: true
